[all]
Account1PK=<Private key for main account (should be set up on Ropsten via Metamask>
Account2PK=<Private key for secondary account (should be set up on Ropsten via Metamask>
Account3PK=<Private key for tertiary account (should be set up on Ropsten via Metamask>

[obscuro]
FundedDeploymentAccountPK=<Private key of pre-funded deploy account>
TokenOBXContractAddressL1=<Address of OBX ERC20 contract in the L1>
TokenOBXContractAddressL2=<Address of OBX ERC20 contract in the L2>
TokenETHContractAddressL1=<Address of ETH ERC20 contract in the L1>
TokenETHContractAddressL2=<Address of ETH ERC20 contract in the L2>
ManagementBridgeAddress=<Management bridge address>

[obscuro.local]
FundedDeploymentAccountPK=<Private key of pre-funded deploy account>
TokenOBXContractAddressL1=<Address of OBX ERC20 contract in the L1>
TokenOBXContractAddressL2=<Address of OBX ERC20 contract in the L2>
TokenETHContractAddressL1=<Address of ETH ERC20 contract in the L1>
TokenETHContractAddressL2=<Address of ETH ERC20 contract in the L2>
ManagementBridgeAddress=<Management bridge address>

[ropsten]
ProjectID=<The infura project ID for the user>



